kind: Service
apiVersion: v1
metadata:
  name: java-vote-service
  namespace: XX_NAMESPACE_XX
spec:
  selector:
    app: java-vote-service
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
