apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: java-vote-service-deployment
  namespace: XX_NAMESPACE_XX
spec:
  selector:
    matchLabels:
      app: java-vote-service
  replicas: 2 
  template: # create pods using pod definition in this template
    metadata:
      namespace: XX_NAMESPACE_XX
      labels:
        app: java-vote-service
    spec:
      containers:
      - name: java-vote-service
        image: sabbour.azurecr.io/services/java-vote-service-redis:XX_IMAGETAG_XX
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_HOST
          value: "redis"
      imagePullSecrets:
        - name:  acr-secret